MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50" 
  #WEIGHT: "../models/sar_res50_noinv3/model_0022500.pth" 
  DOMAIN_ADAPTATION_ON: True
  INVERSION_BACKBONE_ON: True
  FEW_SHOT_ON: False
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NMS: 0.3
  DA_HEADS:
    DA_IMG_GRL_WEIGHT: 0.1
    DA_INS_GRL_WEIGHT: 0.1
  INVERSION:
    RE_FEATURES_NUMS: 4
    INVERSION_LOSS_WEIGHT: 0.001
    DROPOUT: True

DATALOADER:
  SIZE_DIVISIBILITY: 32
DATASETS:
  TRAIN: ("dior_fine_instanceonly_seg_train_cocostyle",)
  SOURCE_TRAIN: ("dior_fine_instanceonly_seg_train_cocostyle",)
  TARGET_TRAIN: ("ssdd_fine_instanceonly_seg_train_cocostyle",)
  TEST: ("ssdd_fine_instanceonly_seg_val_cocostyle",)

INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: (800)
  MAX_SIZE_TEST: 800
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  STEPS: (50000,)
  MAX_ITER: 70000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 1
